service: docker-selenium-lambda

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${opt:region}
  lambdaHashingVersion: 20201221
  ecr:
    images:
      test:
        path: ./

functions:
  server:
    timeout: 60
    memorySize: 2048
    image:
      name: autoCheck-docker
